export const metadata = {
  title: "WDD430-w2",
  description: "Generated by Emanuel Jonatas",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
